name: buildx latest

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/main.yml
      - .dockerignore
      - Dockerfile
      - run.sh
  schedule:
    - cron: '25 2,14 * * *'
  repository_dispatch:
    types: [start-buildx-workflow]

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'hwdsl2' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Check
        if: success()
        run: |
          if [ ! -x /usr/bin/shellcheck ]; then
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get -yq update
            sudo apt-get -yq install shellcheck
          fi

          cd "$GITHUB_WORKSPACE"
          pwd
          ls -ld vpn.env.example

          export SHELLCHECK_OPTS="-e SC1090,SC1091,SC1117"
          shellcheck --version
          shopt -s globstar
          ls -ld -- **/*.sh
          shellcheck **/*.sh
          shopt -u globstar

  check_update:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'hwdsl2'
    env:
      DOCKER_USER: ${{ github.repository_owner }}
      EVENT_NAME: ${{ github.event_name }}
    outputs:
      should_update: ${{ steps.check.outputs.should_update }}
    steps:
      - name: Prepare
        run: |
          if [ "$EVENT_NAME" != "push" ] && [ "$EVENT_NAME" != "repository_dispatch" ]; then
            docker pull debian:buster-slim
            docker pull "$DOCKER_USER/ipsec-vpn-server"
          fi
          echo "GitHub event name: $EVENT_NAME"
      - name: Check
        id: check
        if: success()
        run: |
          if [ "$EVENT_NAME" != "push" ] && [ "$EVENT_NAME" != "repository_dispatch" ]; then
            DEBIAN_UPDATED=false

            debian_update_time=$(docker inspect --format='{{.Created}}' debian:buster-slim)
            image_update_time=$(docker inspect --format='{{.Created}}' "$DOCKER_USER/ipsec-vpn-server")

            if [ -n "$debian_update_time" ] && [ -n "$image_update_time" ]; then
              debian_update_time_s=$(date -d "$debian_update_time" +%s)
              image_update_time_s=$(date -d "$image_update_time" +%s)
              current_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
              current_time_s=$(date -d "$current_time" +%s)
              diff_time_s=$((current_time_s - debian_update_time_s))
              diff_time=$(printf '%dd %dh:%dm:%ds\n' $(($diff_time_s/86400)) $(($diff_time_s%86400/3600)) $(($diff_time_s%3600/60)) $(($diff_time_s%60)))

              echo "Debian update time:     $debian_update_time"
              echo "Debian update time (s): $debian_update_time_s"
              echo "Image update time:      $image_update_time"
              echo "Image update time (s):  $image_update_time_s"
              echo "Current time:           $current_time"
              echo "Current time (s):       $current_time_s"
              echo "Time diff (cur-debian): $diff_time (${diff_time_s}s)"

              if [ -n "$debian_update_time_s" ] && [ -n "$image_update_time_s" ] \
                && [ "$debian_update_time_s" -ge "$image_update_time_s" ] \
                && [ "$diff_time_s" -ge 14400 ]; then
                echo "Starting build..."
                DEBIAN_UPDATED=true
              else
                echo "Not starting build."
              fi
            fi
            echo ::set-output name=should_update::${DEBIAN_UPDATED}
          else
            echo "Starting build..."
            echo ::set-output name=should_update::true
          fi

  vpn_test:
    needs: check_update
    if: needs.check_update.outputs.should_update == 'true'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_id: [no-env, with-env]
      fail-fast: false
    env:
      TEST_ID: ${{ matrix.test_id }}
      EVENT_NAME: ${{ github.event_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Test
        if: success()
        run: |
          [ ! -x /usr/bin/docker ] && exit 1

          cd "$GITHUB_WORKSPACE"
          pwd
          ls -ld vpn.env.example
          sed -i '/swan_ver_url/s/^/#/' run.sh

          docker build -t vpn-test .

          if [ "$TEST_ID" = "with-env" ]; then
            docker run \
            --name "$TEST_ID" \
            --env-file ./vpn.env.example \
            --restart=always \
            -v ikev2-vpn-data:/etc/ipsec.d \
            -p 500:500/udp \
            -p 4500:4500/udp \
            -d --cap-add=NET_ADMIN \
            --device=/dev/ppp \
            --sysctl net.ipv4.ip_forward=1 \
            --sysctl net.ipv4.conf.all.accept_redirects=0 \
            --sysctl net.ipv4.conf.all.send_redirects=0 \
            --sysctl net.ipv4.conf.all.rp_filter=0 \
            --sysctl net.ipv4.conf.default.accept_redirects=0 \
            --sysctl net.ipv4.conf.default.send_redirects=0 \
            --sysctl net.ipv4.conf.default.rp_filter=0 \
            --sysctl net.ipv4.conf.eth0.send_redirects=0 \
            --sysctl net.ipv4.conf.eth0.rp_filter=0 \
            vpn-test
          elif [ "$TEST_ID" = "no-env" ]; then
            docker run \
            --name "$TEST_ID" \
            --restart=always \
            -p 500:500/udp \
            -p 4500:4500/udp \
            -d --cap-add=NET_ADMIN \
            --device=/dev/ppp \
            --sysctl net.ipv4.ip_forward=1 \
            --sysctl net.ipv4.conf.all.accept_redirects=0 \
            --sysctl net.ipv4.conf.all.send_redirects=0 \
            --sysctl net.ipv4.conf.all.rp_filter=0 \
            --sysctl net.ipv4.conf.default.accept_redirects=0 \
            --sysctl net.ipv4.conf.default.send_redirects=0 \
            --sysctl net.ipv4.conf.default.rp_filter=0 \
            --sysctl net.ipv4.conf.eth0.send_redirects=0 \
            --sysctl net.ipv4.conf.eth0.rp_filter=0 \
            vpn-test
          fi

          sleep 60
          docker ps | grep "$TEST_ID"
          docker logs "$TEST_ID"
          docker exec "$TEST_ID" netstat -anpu | grep pluto
          docker exec "$TEST_ID" netstat -anpu | grep xl2tpd
          docker exec "$TEST_ID" iptables -nL
          docker exec "$TEST_ID" iptables -nL | grep -q '192\.168\.42\.0/24'
          docker exec "$TEST_ID" iptables -nL -t nat
          docker exec "$TEST_ID" iptables -nL -t nat | grep -q '192\.168\.43\.0/24'
          docker exec "$TEST_ID" ipsec status
          docker exec "$TEST_ID" ipsec status | grep -q l2tp-psk
          docker exec "$TEST_ID" ipsec status | grep -q xauth-psk
          if [ "$TEST_ID" = "with-env" ]; then
            source ./vpn.env.example
            docker exec "$TEST_ID" grep "$VPN_IPSEC_PSK" /etc/ipsec.secrets
            docker exec "$TEST_ID" grep "$VPN_USER" /etc/ppp/chap-secrets
            docker exec "$TEST_ID" grep "$VPN_PASSWORD" /etc/ppp/chap-secrets
            docker exec "$TEST_ID" grep "$VPN_USER" /etc/ipsec.d/passwd
            docker exec "$TEST_ID" ipsec status | grep -q ikev2-cp
          fi

          docker restart "$TEST_ID"

          sleep 15
          docker ps | grep "$TEST_ID"
          docker logs "$TEST_ID"
          docker exec "$TEST_ID" netstat -anpu | grep pluto
          docker exec "$TEST_ID" netstat -anpu | grep xl2tpd
          docker exec "$TEST_ID" iptables -nL
          docker exec "$TEST_ID" iptables -nL | grep -q '192\.168\.42\.0/24'
          docker exec "$TEST_ID" iptables -nL -t nat
          docker exec "$TEST_ID" iptables -nL -t nat | grep -q '192\.168\.43\.0/24'
          docker exec "$TEST_ID" ipsec status
          docker exec "$TEST_ID" ipsec status | grep -q l2tp-psk
          docker exec "$TEST_ID" ipsec status | grep -q xauth-psk
          if [ "$TEST_ID" = "with-env" ]; then
            docker exec "$TEST_ID" grep "$VPN_IPSEC_PSK" /etc/ipsec.secrets
            docker exec "$TEST_ID" grep "$VPN_USER" /etc/ppp/chap-secrets
            docker exec "$TEST_ID" grep "$VPN_PASSWORD" /etc/ppp/chap-secrets
            docker exec "$TEST_ID" grep "$VPN_USER" /etc/ipsec.d/passwd
            docker exec "$TEST_ID" ipsec status | grep -q ikev2-cp
          fi
      - name: Clear
        if: always()
        run: |
          docker rm -f "$TEST_ID" || true
          docker rmi vpn-test || true

  buildx:
    needs: [check_update, vpn_test]
    if: needs.check_update.outputs.should_update == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Buildx
        if: success()
        run: |
          [ ! -x /usr/bin/docker ] && exit 1
          if [ ! -x /usr/bin/wget ] || [ ! -x /usr/bin/jq ]; then
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get -yq update
            sudo apt-get -yq install wget jq
          fi

          DOCKER_DIR="${HOME}/.docker/cli-plugins"
          BUILDX_VER=$(wget -t 3 -T 30 -qO- "https://api.github.com/repos/docker/buildx/releases/latest" | jq -r ".tag_name")
          [ -z "${BUILDX_VER}" ] && exit 1
          echo "Buildx version: ${BUILDX_VER}"

          mkdir -p "${DOCKER_DIR}"
          BUILDX_URL="https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64"
          wget -t 3 -T 30 -nv -O "${DOCKER_DIR}/docker-buildx" "${BUILDX_URL}"
          chmod a+x "${DOCKER_DIR}/docker-buildx"

          docker info
          docker buildx version

          docker pull -q multiarch/qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
          docker buildx create --name "builder-${GITHUB_SHA::8}" --driver docker-container --use
          docker buildx inspect --bootstrap
      - name: Docker Hub Login
        if: success()
        env:
          DOCKER_USER: ${{ github.repository_owner }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USER" --password-stdin 2>&1
      - name: Quay.io Login
        if: success()
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
        run: echo "$QUAY_TOKEN" | docker login quay.io --username "$QUAY_USER" --password-stdin 2>&1
      - name: Docker Buildx (build and push)
        if: success()
        env:
          DOCKER_USER: ${{ github.repository_owner }}
        run: |
          cd "$GITHUB_WORKSPACE"
          pwd
          ls -ld vpn.env.example
          current_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BUILD_DATE=$current_time \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg VERSION=latest \
            -t "$DOCKER_USER/ipsec-vpn-server:latest" \
            --push \
            .

          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BUILD_DATE=$current_time \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg VERSION=latest \
            -t "quay.io/$DOCKER_USER/ipsec-vpn-server:latest" \
            --push \
            .
      - name: Clear
        if: always()
        run: |
          shred -u "${HOME}/.docker/config.json"
          rm -f "${HOME}/.docker/config.json"
          docker buildx rm "builder-${GITHUB_SHA::8}" || true
