#
# Copyright (C) 2020-2023 Lin Song <linsongui@gmail.com>
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 3.0
# Unported License: http://creativecommons.org/licenses/by-sa/3.0/
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!

name: build debian

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/main-debian.yml'
      - '.github/workflows/buildx.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/vpn_test.yml'
      - '.dockerignore'
      - 'Dockerfile.debian'
      - 'run.sh'

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  vpn_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/vpn_test.yml
    with:
      os_type: debian

  buildx:
    needs: [shellcheck, vpn_test]
    uses: ./.github/workflows/buildx.yml
    with:
      os_type: debian
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      BUILD_ONLY: ${{ secrets.BUILD_ONLY }}
